### ISSUE TITLE
broken view under github insights

### ISSUE THREAD

**Issue by RokkuCode** [Mai-Lapyst/github-oldstyle#1]
Thanks for your great work bringing the old github interface back.

there is a small issue with this style. the github insights views does not work:

![grafik](https://user-images.githubusercontent.com/3813927/86553221-661ec880-bf4a-11ea-919b-ea7df555a0c0.png)

**Comment by Mai-Lapyst** [comment]
thanks for information!

updated with new version in commit 2c52766915c527c5af02b5dbc888afe87990e25c
